language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - NODE_OPTIONS=-max_old_space_size=4096
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master